services:
  db:
    image: 'postgis/postgis:16-3.4'
    environment:
      - 'POSTGRES_DB=wego-coding-exercise'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5433:5432'
    volumes:
      - db:/data/postgres

volumes:
  db:
