services:
  db:
    image: 'postgis/postgis:16-3.4'
    environment:
      - 'POSTGRES_DB=wego-coding-exercise'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5433:5432'
    volumes:
      - db:/data/postgres
  redis:
    image: 'redis'
    volumes:
      - redis:/data/redis
    ports:
      - '6380:6379'

volumes:
  db:
  redis:
